#! /bin/sh

# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"
# echo  $BSPWM_CONFIG


# Kill if already running
killall -9  picom  sxhkd  dunst  redshift   xfce4-power-manager
# sxhkd &
# Launch keybinding daemon
sxhkd -c   ~/.config/bspwm/sxhkdrc &

xsetroot -cursor_name left_ptr
# wmname LG3D


# Script for external rules
bspc config external_rules_command "$BSPWM_CONFIG/scripts/external_rules"

#========================================================================================
# ==================   桌面  =================
#========================================================================================
# 以下示例配置将会配置10个桌面在单独的显示器上：
# bspc monitor -d 1:Browser  2:Code 3:Term  4:File  5:Chat  6:AuVideo  7  8  9
# bspc monitor -d 1  2  3:Term  4:File  5:Chat  6:AuVideo  7  8  9

bspc monitor -d I II III IV V VI VII VIII IX X

# 如果使用多显示器，则需要为每一个显示器配置：
# bspc monitor DVI-I-1 -d I II III IV
# bspc monitor DVI-I-2 -d V VI VII
# bspc monitor DP-1 -d VIII IX X


bspc config top_padding        22
bspc config bottom_padding     1
bspc config left_padding       0
bspc config right_padding      1

# 给当前活动窗口加一个1px的红色框
bspc config border_width         2

# 设置窗口之间的空隙为10px
bspc config window_gap            2

# Focusing behavior
# bspc config focus_follows_pointer false
bspc config focus_follows_pointer   true
bspc config ignore_ewmh_focus       true
bspc config pointer_follows_monitor true

# bspc config normal_border_color "#282828"
# bspc config focused_border_color "#00ff00"
# bspc config active_border_color "#000000"
# bspc config presel_feedback_color "#FABD2F"

# Border colors
bspc config normal_border_color "#484848"
# bspc config focused_border_color "#1F8999"
bspc config focused_border_color "#00ff00"
bspc config active_border_color "#26E2FF"


# Misc
bspc config split_ratio 0.50
bspc config initial_polarity   second_child

# Borders and gaps
bspc config borderless_monocle       true
bspc config gapless_monocle          true
bspc config paddingless_monocle      true
bspc config single_monocle           false
unclutter --ignore-scrooling &

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true




#========================================================================================
# 设置窗口规则 
#========================================================================================
bspc rule -a firefox desktop='^1'
bspc rule -a Nightly desktop='^1' state=tiled
bspc rule -a FirefoxNightly state=tiled

# 下面为一些程序的窗口的特殊设置
# 将vlc和图片浏览设置为浮动窗口
bspc rule -a vlc                 state=floating
bspc rule -a mplayer             state=floating
bspc rule -a smplayer            state=floating
bspc rule -a netease-cloud-music state=floating
bspc rule -a Sxiv                state=floating
bspc rule -a Screenkey           manage=off
bspc rule -a mplayer2            state=floating


# 虚拟机也需要使用浮动窗口
bspc rule -a "VirtualBox Manager" state=floating manage=off
bspc rule -a "VirtualBox Machine" state=floating manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Xfce4-about state=floating
bspc rule -a Steam desktop='^5' state=floating
bspc rule -a spotify desktop='^4' state=pseudo_tiled
bspc rule -a Qq state=floating desktop='^8'

#===================================================================================
#==========   Autostart  Proram =============================
#====================================================================================


bash $HOME/.config/bspwm/scripts/autostart.sh


##panel

#PANEL_HEIGHT=26
#PANEL_FIFO="~/tmp/panel-fifo"
#PANEL_FONT="DejaVu Sans Mono:size=9"

#bspc config top_padding $PANEL_HEIGHT

#killall bspwmstatus dzen2 bspc xtitle

#[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
#mkfifo "$PANEL_FIFO"

#bspc control --subscribe > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &  # Optional: for window title
#bspwmstatus | dzen2 -fn "$PANEL_FONT" -h $PANEL_HEIGHT -ta l &

#panel dzen2





# bspdir=~/.config/bspwm
# # launch dzen2 panels
# $bspdir/panels/topbar &
#     $bspdir/panels/status &
